# Cargo Tool Configuration for Ahma MCP
command = "cargo"
enabled = true

# Common cargo subcommands
[[subcommand]]
name = "build"
description = "Build the project"
[[subcommand.options]]
name = "release"
type = "boolean"
description = "Build with optimizations enabled"
[[subcommand.options]]
name = "features"
type = "string"
description = "Space-separated list of features to enable"
[[subcommand.options]]
name = "workspace"
type = "boolean"
description = "Build all packages in the workspace"

[[subcommand]]
name = "test"
description = "Run tests"
[[subcommand.options]]
name = "release"
type = "boolean" 
description = "Run tests with optimizations"
[[subcommand.options]]
name = "workspace"
type = "boolean"
description = "Run tests for all packages in workspace"

[[subcommand]]
name = "check"
description = "Check code without building"
[[subcommand.options]]
name = "release"
type = "boolean"
description = "Check with release profile"
[[subcommand.options]]
name = "workspace"
type = "boolean"
description = "Check all packages in workspace"

[[subcommand]]
name = "clippy"
description = "Run Clippy linter"
[[subcommand.options]]
name = "fix"
type = "boolean"
description = "Automatically fix warnings"
[[subcommand.options]]
name = "allow-dirty"
type = "boolean"
description = "Allow fixing when working directory is dirty"

[[subcommand]]
name = "fmt" 
description = "Format code using rustfmt"
[[subcommand.options]]
name = "check"
type = "boolean"
description = "Check if files are formatted without changing them"

[[subcommand]]
name = "run"
description = "Run the project"
[[subcommand.options]]
name = "release"
type = "boolean"
description = "Run with optimizations"
[[subcommand.options]]
name = "bin"
type = "string"
description = "Name of the binary to run"

[[subcommand]]
name = "doc"
description = "Generate documentation"
[[subcommand.options]]
name = "no-deps"
type = "boolean"
description = "Don't build documentation for dependencies"
[[subcommand.options]]
name = "open"
type = "boolean"
description = "Open documentation in browser"

# AI guidance hints
[hints]
primary = "Cargo is Rust's build tool and package manager"
usage = "Common commands: build, test, run, check, clippy, fmt"
