# Cat Tool Configuration for Ahma MCP
# This configuration adapts the `cat` command for AI assistant use
# When ahma_mcp starts, it will automatically discover cat's capabilities
# by parsing `cat --help` output and update this file with discovered commands

tool_name = "cat"
command = "cat"
enabled = true
timeout_seconds = 60
verbose = false

# AI guidance hints - customize these to improve AI interactions
[hints]
# Primary hint shown when AI considers using cat
primary = "Display file contents, concatenate files, or create files. Use cat to read text files, combine multiple files, or output content for processing."

# Usage examples for common operations
usage = """
Common cat commands:
- cat file.txt - Display contents of a file
- cat file1.txt file2.txt - Display multiple files in sequence
- cat -n file.txt - Display file with line numbers
- cat -b file.txt - Number only non-blank lines
- cat -s file.txt - Squeeze multiple blank lines into one
- cat -A file.txt - Show all characters including tabs and line endings
- cat > newfile.txt - Create new file (type content, then Ctrl+D)
- cat file1.txt file2.txt > combined.txt - Concatenate files into new file
"""

# What the AI should think about during operations
wait_hint = "While cat runs, consider: file size (large files may take time), whether you need line numbers, or if you're combining files for further processing."

# Parameter-specific hints for better AI understanding
[hints.parameters]
number = "Use -n to show line numbers for all lines"
number_nonblank = "Use -b to number only non-blank lines"
squeeze_blank = "Use -s to squeeze multiple consecutive blank lines into one"
show_all = "Use -A to show all characters including tabs (^I) and line endings ($)"
show_ends = "Use -E to show line endings with $ symbol"
show_tabs = "Use -T to show tabs as ^I"

# Override configurations for specific scenarios
# Uncomment and customize as needed:

# [overrides.large_file]
# timeout_seconds = 300  # Large files may take longer
# hints.primary = "Display contents of large files - consider using head, tail, or less for very large files"
# hints.wait_hint = "For large files, consider if you need the entire content or just portions"

# [overrides.multiple_files]
# timeout_seconds = 120
# hints.primary = "Concatenate and display multiple files in sequence"
# hints.usage = "cat file1 file2 file3 to combine files, or redirect output with > to save"

# Example of advanced usage:
# [hints.examples]
# view_config = "View configuration files: cat ~/.bashrc ~/.zshrc"
# combine_logs = "Combine log files: cat *.log > combined.log"
# create_file = "Create small files: cat > filename.txt (then type content and Ctrl+D)"
# filter_content = "Combine with other tools: cat file.txt | grep pattern"
