# Echo Tool Configuration for Ahma MCP
command = "echo"
enabled = true

[[subcommand]]
name = "message"
description = "Echo text to stdout"
[[subcommand.options]]
name = "text"
type = "string" 
description = "Text to echo"
