# Git Tool Configuration for Ahma MCP
command = "git"
enabled = true

[[subcommand]]
name = "status"
description = "Show working tree status"

[[subcommand]]
name = "add"
description = "Add file contents to the index"
[[subcommand.options]]
name = "all"
type = "boolean"
description = "Add all changes in working directory"
[[subcommand.options]]
name = "patch"
type = "boolean"
description = "Interactively choose hunks to add"

[[subcommand]]
name = "commit"
description = "Record changes to the repository"
[[subcommand.options]]
name = "message"
type = "string"
description = "Commit message"
[[subcommand.options]]
name = "all"
type = "boolean"
description = "Automatically stage modified files"

[[subcommand]]
name = "push"
description = "Update remote refs with local commits"
[[subcommand.options]]
name = "force"
type = "boolean"
description = "Force push (use with caution)"

[[subcommand]]
name = "pull"
description = "Fetch and integrate with another repository"

[[subcommand]]
name = "log"
description = "Show commit logs"
[[subcommand.options]]
name = "oneline"
type = "boolean"
description = "Show logs in oneline format"