# LS Tool Configuration for Ahma MCP
command = "ls"
enabled = true

[[subcommand]]
name = "ls"
description = "List directory contents and file information"
[[subcommand.options]]
name = "all"
type = "boolean"
description = "Show hidden files and directories"
[[subcommand.options]]
name = "long"
type = "boolean"
description = "Use long listing format"
[[subcommand.options]]
name = "human_readable"
type = "boolean"
description = "Show file sizes in human-readable format"

# AI guidance hints
[hints]
primary = "List directory contents and file information"
usage = "Common options: -l (long format), -a (all files), -h (human readable)"
